{
    "name": "库存子仓库层级",
    "summary": "使用库存库位树跟踪仓库和子仓库。",
    "version": "19.0.1.0.41",
    "category": "库存/库存",
    "author": "Local",
    "license": "LGPL-3",
    "depends": [
        "base_import",
        "contacts",
        "mass_mailing",
        "stock",
        "web_hierarchy",
        "mrp",
        "sale_stock",
        "website_sale",
        "website_sale_wishlist",
        "spreadsheet_dashboard",
        "spreadsheet_dashboard_sale",
        "website",
        "auth_signup",
        "account_payment",
        "payment_wechatpay",
        "payment_alipay",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/currency_data.xml",
        "data/branding_data.xml",
        "data/language_data.xml",
        "data/distributor_data.xml",
        "data/sale_nature_data.xml",
        "data/external_sales_dashboard.xml",
        "views/branding_views.xml",
        "views/erp_login_views.xml",
        "views/bom_reusable_template_views.xml",
        "views/distributor_views.xml",
        "views/supplier_views.xml",
        "views/app_menu_views.xml",
        "views/descendant_inventory_total_views.xml",
        "views/product_attribute_apply_views.xml",
        "views/product_import_result_views.xml",
        "views/business_import_result_views.xml",
        "views/product_quick_encoder_views.xml",
        "views/product_bulk_update_views.xml",
        "views/product_international_mapping_views.xml",
        "views/import_format_export_actions.xml",
        "views/stock_quant_views.xml",
        "views/stock_internal_transfer_wizard_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_location_views.xml",
        "views/stock_warehouse_views.xml",
        "views/warehouse_history_views.xml",
        "views/sale_order_views.xml",
        "views/external_sale_report_views.xml",
        "views/website_video_views.xml",
        "views/website_collections_views.xml",
        "views/website_shop_group_views.xml",
        "views/website_cart_stock_warning_views.xml",
        "views/website_product_engagement_views.xml",
        "views/website_international_mapping_views.xml",
        "views/website_stores_views.xml",
        "views/website_payment_receipt_views.xml",
        "views/website_payment_refund_views.xml",
        "views/website_refund_request_views.xml",
        "views/website_purchase_history_views.xml",
        "data/website_public_access_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "stock_subwarehouse_hierarchy/static/src/js/advanced_search_boolean.js",
            "stock_subwarehouse_hierarchy/static/src/js/business_import_start_row.js",
            "stock_subwarehouse_hierarchy/static/src/js/product_import_result.js",
            "stock_subwarehouse_hierarchy/static/src/js/source_location_many2one.js",
            "stock_subwarehouse_hierarchy/static/src/js/template_format_export_menu.js",
            "stock_subwarehouse_hierarchy/static/src/xml/template_format_export_menu.xml",
            "stock_subwarehouse_hierarchy/static/src/xml/business_import_start_row.xml",
            "stock_subwarehouse_hierarchy/static/src/xml/advanced_search_boolean.xml",
        ],
        "web.assets_frontend": [
            "stock_subwarehouse_hierarchy/static/src/js/cart_stock_warning.js",
            "stock_subwarehouse_hierarchy/static/src/scss/cart_stock_warning.scss",
        ],
    },
    "installable": True,
    "application": False,
    "post_init_hook": "post_init_hook",
}
