{
    "name": "库存子仓库层级",
    "summary": "使用库存库位树跟踪仓库和子仓库。",
    "version": "19.0.1.0.0",
    "category": "库存/库存",
    "author": "Local",
    "license": "LGPL-3",
    "depends": [
        "stock",
        "web_hierarchy",
        "mrp",
        "sale_stock",
        "website_sale",
        "spreadsheet_dashboard",
        "website",
        "account_payment",
        "payment_wechatpay",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/currency_data.xml",
        "data/branding_data.xml",
        "data/language_data.xml",
        "views/branding_views.xml",
        "views/descendant_inventory_total_views.xml",
        "views/product_attribute_apply_views.xml",
        "views/import_format_export_actions.xml",
        "views/stock_quant_views.xml",
        "views/stock_location_views.xml",
        "views/stock_warehouse_views.xml",
        "views/sale_order_views.xml",
        "views/website_video_views.xml",
        "views/website_collections_views.xml",
        "views/website_shop_group_views.xml",
        "views/website_stores_views.xml",
        "views/website_payment_receipt_views.xml",
        "data/website_public_access_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "stock_subwarehouse_hierarchy/static/src/js/source_location_many2one.js",
            "stock_subwarehouse_hierarchy/static/src/js/template_format_export_menu.js",
            "stock_subwarehouse_hierarchy/static/src/xml/template_format_export_menu.xml",
        ],
    },
    "installable": True,
    "application": False,
    "post_init_hook": "post_init_hook",
}
