from . import mrp_bom
from . import mrp_production
from . import payment_transaction
from . import ir_http
from . import product_template
from . import product_website_code_mapping
from . import product_international_mapping_import
from . import product_template_attribute_line
from . import res_company
from . import res_lang
from . import res_users
from . import res_currency
from . import sale_order
from . import sale_order_line
from . import stock_location
from . import stock_move
from . import stock_picking
from . import stock_quant
from . import stock_rule
from . import stock_warehouse
from . import stock_subwarehouse_inventory_total
from . import website_page
from . import website_payment_refund_wizard
from . import website_refund_request
