from . import mrp_production
from . import product_template
from . import res_currency
from . import sale_order
from . import sale_order_line
from . import stock_location
from . import stock_move
from . import stock_picking
from . import stock_quant
from . import stock_rule
from . import stock_warehouse
from . import stock_subwarehouse_inventory_total
